name: deploy-book

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy-book:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      # Install Python
      - name: Set up Python 3.9
        uses: actions/setup-python@v5
        with:
          python-version: '3.9'   # or '3.9.23'
          cache: 'pip'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Build the book
        run: |
          jupyter-book build .

      # Prevent GitHub Pages from running Jekyll on the site, Jekyll not necessary for jupyter-book.
      - name: Disable Jekyll on the published site
        run: touch _build/html/.nojekyll

      # Publish to external repo (user/organization pages)
      - name: Deploy to GitHub Pages
        if: ${{ github.event_name == 'push' }}
        uses: peaceiris/actions-gh-pages@v3
        with:
          # For external repositories, use a deploy key or a PAT, not GITHUB_TOKEN.
          deploy_key: ${{ secrets.DEPLOY_DOCS }}
          external_repository: engdeanalytics/engdeanalytics.github.io
          publish_branch: main        # for user/org pages repo, 'main' is typical
          publish_dir: ./_build/html
